services:
  backend:
    build:
      context: ./backend      # Points to the backend folder
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    networks:
      - my-network

  frontend:
    build:
      context: ./frontend      # Points to the frontend folder
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

